#!/bin/bash

if [ ! -d "/sys/class/pwm/pwmchip1/pwm0" ]; then
    echo 0 > /sys/class/pwm/pwmchip1/export
    echo 50000 > /sys/class/pwm/pwmchip1/pwm0/period
    echo 30000 > /sys/class/pwm/pwmchip1/pwm0/duty_cycle
    echo 1 > /sys/class/pwm/pwmchip1/pwm0/enable
    exit 0
fi